(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.DHLMatchCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const TEAM_PATTERNS=[['bo dao nha','portugal'],['tay ban nha','spain'],['nhat ban','japan'],['nhat','japan'],['ha lan','netherlands'],['argentina','argentina'],['brazil','brazil'],['mexico','mexico'],['croatia','croatia'],['crotia','croatia'],['phap','france'],['duc','germany'],['anh','england'],['bi','belgium'],['y','italy']];
const COLOR_WORDS=new Set(['do','trang','xanh','vang','den','be','sua','reu','cam','ngoc','than','soc','siu','la','duong','dam','nhat']);
const STOP=new Set(['bo','quan','ao','bong','da','vai','thun','me','han','quoc','nhan','in','ten','so','dt','clb','hd','wc','world','cup','mau','2026','26','2025','25','2024','24']);
function plain(v){return String(v||'').toLowerCase().replace(/đ/g,'d').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function teamOf(v){const p=' '+plain(v)+' ';for(const [pat,id] of TEAM_PATTERNS)if(p.includes(' '+pat+' '))return id;return '';}
function modeOf(v){const p=plain(v);if(/\btap\b/.test(p))return'training';if(/san khach|\bkhach\b/.test(p))return'away';if(/san nha|\bnha\b/.test(p))return'home';return'';}
function yearOf(v){const p=plain(v);if(/\b2026\b|\b26\b/.test(p))return'2026';if(/\b2025\b|\b25\b/.test(p))return'2025';return'';}
function colorsOf(v){return new Set(plain(v).split(' ').filter(x=>COLOR_WORDS.has(x)));}
function contentTokens(v){return new Set(plain(v).split(' ').filter(x=>x.length>1&&!STOP.has(x)&&!COLOR_WORDS.has(x)));}
function jaccard(a,b){if(!a.size&&!b.size)return 0;let inter=0;for(const x of a)if(b.has(x))inter++;return inter/(a.size+b.size-inter||1);}
function colorScore(a,b){if(!a.size||!b.size)return 0;let inter=0;for(const x of a)if(b.has(x))inter++;if(inter===0){if((a.has('than')||a.has('den'))&&(b.has('than')||b.has('den')))return.35;return 0;}return Math.min(1,inter/Math.max(1,Math.min(a.size,b.size)));}
function scoreProductMatch(sapoName,sapoSku,sourceName,sourceColor){const sText=`${sapoName||''} ${sapoSku||''}`,tText=`${sourceName||''} ${sourceColor||''}`;const st=teamOf(sText),tt=teamOf(tText);if(st&&tt&&st!==tt)return 0;let score=0;if(st&&tt&&st===tt)score+=.50;const sy=yearOf(sText),ty=yearOf(tText);if(sy&&ty)score+=sy===ty?.12:-.12;const sm=modeOf(sText),tm=modeOf(tText);if(sm&&tm)score+=sm===tm?.10:-.08;score+=.22*colorScore(colorsOf(sText),colorsOf(tText));score+=.06*jaccard(contentTokens(sText),contentTokens(tText));return Math.max(0,Math.min(1,score));}
function normalizeSize(v){const p=plain(v).replace(/\s+/g,'').toUpperCase();return({'2XL':'XXL','3XL':'XXXL','4XL':'XXXXL','5XL':'XXXXXL'})[p]||p;}
function groupSourceVariants(results){const groups=[];for(const product of results||[]){const byColor=new Map();for(const v of product.variants||[]){const color=String(v.color||'').trim()||'(không màu)';if(!byColor.has(color))byColor.set(color,[]);byColor.get(color).push(v);}for(const [color,variants] of byColor)groups.push({parentId:product.parentId,parentName:product.parentName||'',color,variants});}return groups;}
function matchSapoProducts(sapoProducts,sourceResults,{minScore=.56,minMargin=.06}={}){const groups=groupSourceVariants(sourceResults),out=[];for(const p of sapoProducts||[]){const sampleSku=(p.variants&&p.variants[0]&&p.variants[0].sku)||'';const ranked=groups.map(g=>({...g,score:scoreProductMatch(p.name,sampleSku,g.parentName,g.color)})).sort((a,b)=>b.score-a.score);const best=ranked[0]||null,second=ranked[1]||null,margin=best?best.score-(second?second.score:0):0,matched=!!best&&best.score>=minScore&&margin>=minMargin;const variantMatches=[];if(matched){for(const sv of p.variants||[]){const size=normalizeSize(sv.size),candidates=best.variants.filter(v=>normalizeSize(v.size)===size);variantMatches.push({sapo:sv,source:candidates.length===1?candidates[0]:null,reason:candidates.length===1?'size':'size-not-unique'});}}out.push({sapoProduct:p,matched,best,second,margin,variantMatches,complete:matched&&variantMatches.length>0&&variantMatches.every(x=>x.source)});}return out;}
return{plain,teamOf,modeOf,yearOf,colorsOf,scoreProductMatch,normalizeSize,groupSourceVariants,matchSapoProducts};
});