import { ArrowRight, Layers3, Sparkles, WandSparkles } from "lucide-react";
import StoreLayout from "@/components/StoreLayout";
import { Badge } from "@/components/ui/badge";

const PET_TRAM_URL = "/manus-storage/pet-tram-pro-x_89dce948.html";

export default function ToolsLibrary() {
  return <StoreLayout><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><section className="relative overflow-hidden rounded-2xl border border-cyan-200 bg-gradient-to-br from-cyan-50 via-white to-violet-50 p-6 sm:p-9"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-cyan-200/40 blur-3xl" /><div className="relative max-w-3xl"><Badge className="bg-cyan-100 text-cyan-800"><Sparkles className="mr-1 h-3.5 w-3.5" />DHL Stores · Công cụ</Badge><h1 className="mt-4 font-display text-4xl font-black uppercase leading-none text-slate-900 sm:text-5xl">Thư viện công cụ thiết kế</h1><p className="mt-4 text-sm leading-relaxed text-slate-600 sm:text-base">Không chỉ là một Tool đơn lẻ. Đây là nơi tập hợp các công cụ hỗ trợ xử lý ảnh, tạo tram, chuẩn bị file in và tối ưu quy trình thiết kế thể thao.</p></div></section><section className="mt-8"><div className="mb-4 flex items-end justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[0.16em] text-cyan-700">Công cụ đang dùng</p><h2 className="mt-1 font-display text-2xl font-black uppercase text-slate-900">Sẵn sàng mở</h2></div><div className="hidden items-center gap-2 text-xs font-bold text-slate-500 sm:flex"><Layers3 className="h-4 w-4 text-cyan-600" />Thư viện sẽ tiếp tục được bổ sung</div></div><div className="grid gap-5 md:grid-cols-2"><a href={PET_TRAM_URL} className="group"><article className="h-full rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white shadow-sm transition-all duration-200 hover:-translate-y-1 hover:border-cyan-400 hover:shadow-lg"><div className="flex items-start justify-between gap-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-cyan-400 text-slate-950"><WandSparkles className="h-6 w-6" /></div><Badge className="bg-emerald-400 text-emerald-950">Đang hoạt động</Badge></div><h3 className="mt-6 font-display text-3xl font-black uppercase">PET TRAM PRO X</h3><p className="mt-2 text-sm leading-relaxed text-slate-300">Xử lý ảnh, tạo tram, vector hóa, thử mockup áo và xuất file phục vụ in ấn.</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-black text-cyan-300">Chạy toàn màn hình <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></article></a><article className="rounded-2xl border border-dashed border-slate-300 bg-white p-6"><div className="grid h-12 w-12 place-items-center rounded-xl bg-slate-100 text-slate-500"><Layers3 className="h-6 w-6" /></div><h3 className="mt-6 font-display text-2xl font-black uppercase text-slate-800">Sắp bổ sung thêm Tool</h3><p className="mt-2 text-sm leading-relaxed text-slate-500">Các công cụ mới sẽ được thêm tại đây khi bạn cung cấp hoặc yêu cầu tính năng phù hợp cho quy trình thiết kế.</p></article></div></section></main></StoreLayout>;
}
