import fs from "node:fs";
const path = "client/src/pages/AdminOrders.tsx";
let s = fs.readFileSync(path, "utf8");
s = s.replace('value={bulkSkuPrice} onChange={event => setBulkSkuPrice(event.target.value)} placeholder="Giá SKU mới" />', 'value={bulkSkuPrice} onChange={event => setBulkSkuPrice(event.target.value)} placeholder="Giá SKU mới" /><Input type="number" min="0" value={bulkSkuCost} onChange={event => setBulkSkuCost(event.target.value)} placeholder="Giá vốn mới" />');
s = s.replace('<div className="mt-2 grid grid-cols-2 gap-2"><label className="text-[10px] font-bold text-slate-500">Giá SKU', '<div className="mt-2 grid grid-cols-3 gap-2"><label className="text-[10px] font-bold text-slate-500">Giá SKU');
s = s.replace('</label><label className="text-[10px] font-bold text-slate-500">Tồn kho<Input type="number" min="0" value={draft.stock}', '</label><label className="text-[10px] font-bold text-amber-700">Giá vốn<Input type="number" min="0" value={draft.costPrice} onChange={event => setSkuDrafts(current => ({ ...current, [variant.id]: { ...draft, costPrice: event.target.value } }))} className="mt-1 h-9 border-amber-200 bg-amber-50 text-sm font-black text-slate-900" /></label><label className="text-[10px] font-bold text-slate-500">Tồn kho<Input type="number" min="0" value={draft.stock}');
s = s.replace('<div className="grid grid-cols-3 gap-3"><Input type="number" value={variantDraft.priceAdjustment}', '<div className="grid grid-cols-4 gap-3"><Input type="number" value={variantDraft.priceAdjustment}');
s = s.replace('placeholder="Chênh giá" disabled={!selectedVariantProductId} /><Input type="number" min="0" value={variantDraft.stock}', 'placeholder="Chênh giá" disabled={!selectedVariantProductId} /><Input type="number" min="0" value={variantDraft.costPrice} onChange={event => setVariantDraft(prev => ({ ...prev, costPrice: event.target.value }))} placeholder="Giá vốn" disabled={!selectedVariantProductId} /><Input type="number" min="0" value={variantDraft.stock}');
fs.writeFileSync(path, s);
